# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtmeterpNpVda.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialog, QDialogButtonBox, QDoubleSpinBox, QGraphicsView,
    QGroupBox, QLabel, QProgressBar, QPushButton,
    QRadioButton, QSizePolicy, QSpinBox, QToolButton,
    QWidget)

class Ui_QtMeter(object):
    def setupUi(self, QtMeter):
        if not QtMeter.objectName():
            QtMeter.setObjectName(u"QtMeter")
        QtMeter.resize(622, 552)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QtMeter.sizePolicy().hasHeightForWidth())
        QtMeter.setSizePolicy(sizePolicy)
        self.buttonBox = QDialogButtonBox(QtMeter)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(492, 510, 120, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Ok)
        self.dBMeter = QProgressBar(QtMeter)
        self.dBMeter.setObjectName(u"dBMeter")
        self.dBMeter.setGeometry(QRect(10, 30, 602, 23))
        self.dBMeter.setAutoFillBackground(False)
        self.dBMeter.setMinimum(-90)
        self.dBMeter.setMaximum(0)
        self.dBMeter.setValue(-87)
        self.dBMeter.setTextVisible(False)
        self.pbStartStop = QPushButton(QtMeter)
        self.pbStartStop.setObjectName(u"pbStartStop")
        self.pbStartStop.setGeometry(QRect(10, 516, 87, 26))
        self.label = QLabel(QtMeter)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(594, 10, 18, 18))
        self.label_2 = QLabel(QtMeter)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(609, 49, 4, 18))
        self.label_3 = QLabel(QtMeter)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(589, 49, 4, 18))
        self.label_4 = QLabel(QtMeter)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(607, 67, 10, 18))
        self.label_5 = QLabel(QtMeter)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(583, 67, 15, 18))
        self.label_6 = QLabel(QtMeter)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(9, 49, 4, 18))
        self.label_7 = QLabel(QtMeter)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(569, 49, 4, 18))
        self.label_8 = QLabel(QtMeter)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(563, 67, 16, 18))
        self.label_9 = QLabel(QtMeter)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(549, 49, 4, 18))
        self.label_10 = QLabel(QtMeter)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(543, 67, 16, 18))
        self.label_11 = QLabel(QtMeter)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(509, 49, 4, 18))
        self.label_12 = QLabel(QtMeter)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(500, 67, 21, 18))
        self.label_13 = QLabel(QtMeter)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(469, 49, 4, 18))
        self.label_14 = QLabel(QtMeter)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(460, 67, 21, 18))
        self.label_15 = QLabel(QtMeter)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(428, 49, 4, 18))
        self.label_16 = QLabel(QtMeter)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(419, 67, 23, 18))
        self.label_17 = QLabel(QtMeter)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(368, 49, 4, 18))
        self.label_18 = QLabel(QtMeter)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(358, 67, 24, 18))
        self.label_19 = QLabel(QtMeter)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(308, 49, 4, 18))
        self.label_20 = QLabel(QtMeter)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(298, 67, 24, 18))
        self.label_21 = QLabel(QtMeter)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(248, 49, 4, 18))
        self.label_22 = QLabel(QtMeter)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(238, 67, 24, 18))
        self.label_23 = QLabel(QtMeter)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(168, 49, 4, 18))
        self.label_24 = QLabel(QtMeter)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(158, 67, 24, 18))
        self.label_25 = QLabel(QtMeter)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(87, 49, 4, 18))
        self.label_26 = QLabel(QtMeter)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(78, 67, 23, 18))
        self.label_27 = QLabel(QtMeter)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 100, 124, 18))
        self.dsbUpdatePeriod = QDoubleSpinBox(QtMeter)
        self.dsbUpdatePeriod.setObjectName(u"dsbUpdatePeriod")
        self.dsbUpdatePeriod.setGeometry(QRect(233, 95, 65, 27))
        self.dsbUpdatePeriod.setDecimals(3)
        self.dsbUpdatePeriod.setMinimum(0.010000000000000)
        self.dsbUpdatePeriod.setMaximum(1.000000000000000)
        self.dsbUpdatePeriod.setSingleStep(0.010000000000000)
        self.dsbUpdatePeriod.setValue(0.033000000000000)
        self.label_28 = QLabel(QtMeter)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(300, 100, 7, 18))
        self.label_29 = QLabel(QtMeter)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 132, 113, 18))
        self.dsbSampleWindow = QDoubleSpinBox(QtMeter)
        self.dsbSampleWindow.setObjectName(u"dsbSampleWindow")
        self.dsbSampleWindow.setGeometry(QRect(125, 127, 67, 27))
        self.dsbSampleWindow.setDecimals(3)
        self.dsbSampleWindow.setMinimum(0.005000000000000)
        self.dsbSampleWindow.setMaximum(1.000000000000000)
        self.dsbSampleWindow.setSingleStep(0.005000000000000)
        self.dsbSampleWindow.setValue(0.050000000000000)
        self.label_30 = QLabel(QtMeter)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(194, 132, 7, 18))
        self.label_31 = QLabel(QtMeter)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 163, 88, 18))
        self.cbSampleHz = QComboBox(QtMeter)
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.addItem("")
        self.cbSampleHz.setObjectName(u"cbSampleHz")
        self.cbSampleHz.setGeometry(QRect(100, 159, 85, 26))
        self.label_32 = QLabel(QtMeter)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(187, 163, 18, 18))
        self.label_33 = QLabel(QtMeter)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 191, 84, 18))
        self.cbSampleSize = QComboBox(QtMeter)
        self.cbSampleSize.addItem("")
        self.cbSampleSize.addItem("")
        self.cbSampleSize.addItem("")
        self.cbSampleSize.addItem("")
        self.cbSampleSize.addItem("")
        self.cbSampleSize.setObjectName(u"cbSampleSize")
        self.cbSampleSize.setGeometry(QRect(100, 187, 79, 26))
        self.sbFramesPerSecond = QSpinBox(QtMeter)
        self.sbFramesPerSecond.setObjectName(u"sbFramesPerSecond")
        self.sbFramesPerSecond.setEnabled(True)
        self.sbFramesPerSecond.setGeometry(QRect(136, 95, 52, 27))
        self.sbFramesPerSecond.setLayoutDirection(Qt.LeftToRight)
        self.sbFramesPerSecond.setFrame(True)
        self.sbFramesPerSecond.setMinimum(1)
        self.sbFramesPerSecond.setMaximum(100)
        self.sbFramesPerSecond.setValue(30)
        self.label_34 = QLabel(QtMeter)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(190, 100, 18, 18))
        self.label_35 = QLabel(QtMeter)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(213, 100, 15, 18))
        self.cbAutoWindow = QCheckBox(QtMeter)
        self.cbAutoWindow.setObjectName(u"cbAutoWindow")
        self.cbAutoWindow.setGeometry(QRect(211, 130, 170, 24))
        self.cbAutoWindow.setChecked(True)
        self.gvHistory = QGraphicsView(QtMeter)
        self.gvHistory.setObjectName(u"gvHistory")
        self.gvHistory.setGeometry(QRect(70, 225, 542, 45))
        self.pbSettings = QPushButton(QtMeter)
        self.pbSettings.setObjectName(u"pbSettings")
        self.pbSettings.setGeometry(QRect(10, 488, 87, 26))
        self.label_36 = QLabel(QtMeter)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(62, 259, 8, 18))
        self.label_37 = QLabel(QtMeter)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(62, 209, 8, 18))
        self.label_38 = QLabel(QtMeter)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(52, 237, 18, 18))
        self.gbChannels = QGroupBox(QtMeter)
        self.gbChannels.setObjectName(u"gbChannels")
        self.gbChannels.setGeometry(QRect(215, 159, 155, 61))
        self.rbMono = QRadioButton(self.gbChannels)
        self.rbMono.setObjectName(u"rbMono")
        self.rbMono.setGeometry(QRect(10, 28, 64, 24))
        self.rbMono.setChecked(True)
        self.rbStereo = QRadioButton(self.gbChannels)
        self.rbStereo.setObjectName(u"rbStereo")
        self.rbStereo.setGeometry(QRect(76, 28, 69, 24))
        self.gbAbs = QGroupBox(QtMeter)
        self.gbAbs.setObjectName(u"gbAbs")
        self.gbAbs.setGeometry(QRect(116, 479, 184, 55))
        self.lblAbsMin = QLabel(self.gbAbs)
        self.lblAbsMin.setObjectName(u"lblAbsMin")
        self.lblAbsMin.setGeometry(QRect(10, 30, 79, 18))
        self.lblAbsMax = QLabel(self.gbAbs)
        self.lblAbsMax.setObjectName(u"lblAbsMax")
        self.lblAbsMax.setGeometry(QRect(91, 30, 79, 18))
        self.tbResetAbs = QToolButton(self.gbAbs)
        self.tbResetAbs.setObjectName(u"tbResetAbs")
        self.tbResetAbs.setGeometry(QRect(158, 0, 26, 25))
        icon = QIcon(QIcon.fromTheme(u"start-here-symbolic"))
        self.tbResetAbs.setIcon(icon)
        self.tbResetAbs.setArrowType(Qt.NoArrow)
        self.gvSpecHistory = QGraphicsView(QtMeter)
        self.gvSpecHistory.setObjectName(u"gvSpecHistory")
        self.gvSpecHistory.setGeometry(QRect(70, 275, 542, 202))
        self.lblSpecMinF = QLabel(QtMeter)
        self.lblSpecMinF.setObjectName(u"lblSpecMinF")
        self.lblSpecMinF.setGeometry(QRect(54, 271, 16, 18))
        self.label_43 = QLabel(QtMeter)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(62, 460, 8, 18))
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setLayoutDirection(Qt.LeftToRight)
        self.label_43.setTextFormat(Qt.PlainText)
        self.label_43.setScaledContents(False)
        self.label_43.setWordWrap(False)
        self.label_39 = QLabel(QtMeter)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(34, 348, 36, 18))
        self.label_40 = QLabel(QtMeter)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(62, 253, 8, 18))
        self.label_41 = QLabel(QtMeter)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(54, 221, 10, 18))
        self.label_42 = QLabel(QtMeter)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(39, 255, 25, 18))
        self.lblSpecMaxF = QLabel(QtMeter)
        self.lblSpecMaxF.setObjectName(u"lblSpecMaxF")
        self.lblSpecMaxF.setGeometry(QRect(39, 462, 24, 18))
        self.gbSpectrumRatio = QGroupBox(QtMeter)
        self.gbSpectrumRatio.setObjectName(u"gbSpectrumRatio")
        self.gbSpectrumRatio.setGeometry(QRect(8, 376, 61, 77))
        font = QFont()
        font.setPointSize(9)
        self.gbSpectrumRatio.setFont(font)
        self.gbSpectrumRatio.setAlignment(Qt.AlignCenter)
        self.gbSpectrumRatio.setFlat(True)
        self.rbSpectrumRatiodB = QRadioButton(self.gbSpectrumRatio)
        self.rbSpectrumRatiodB.setObjectName(u"rbSpectrumRatiodB")
        self.rbSpectrumRatiodB.setGeometry(QRect(2, 16, 45, 22))
        self.rbSpectrumRatioPower = QRadioButton(self.gbSpectrumRatio)
        self.rbSpectrumRatioPower.setObjectName(u"rbSpectrumRatioPower")
        self.rbSpectrumRatioPower.setGeometry(QRect(2, 39, 65, 22))
        self.gbSpectrumRatio.raise_()
        self.label_36.raise_()
        self.label_43.raise_()
        self.label_37.raise_()
        self.label_40.raise_()
        self.buttonBox.raise_()
        self.dBMeter.raise_()
        self.pbStartStop.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.dsbUpdatePeriod.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.dsbSampleWindow.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.cbSampleHz.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.cbSampleSize.raise_()
        self.sbFramesPerSecond.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.cbAutoWindow.raise_()
        self.gvHistory.raise_()
        self.pbSettings.raise_()
        self.label_38.raise_()
        self.gbChannels.raise_()
        self.gbAbs.raise_()
        self.gvSpecHistory.raise_()
        self.lblSpecMinF.raise_()
        self.label_39.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.lblSpecMaxF.raise_()
        QWidget.setTabOrder(self.pbStartStop, self.pbSettings)
        QWidget.setTabOrder(self.pbSettings, self.sbFramesPerSecond)
        QWidget.setTabOrder(self.sbFramesPerSecond, self.dsbUpdatePeriod)
        QWidget.setTabOrder(self.dsbUpdatePeriod, self.dsbSampleWindow)
        QWidget.setTabOrder(self.dsbSampleWindow, self.cbAutoWindow)
        QWidget.setTabOrder(self.cbAutoWindow, self.cbSampleHz)
        QWidget.setTabOrder(self.cbSampleHz, self.cbSampleSize)
        QWidget.setTabOrder(self.cbSampleSize, self.rbMono)
        QWidget.setTabOrder(self.rbMono, self.rbStereo)
        QWidget.setTabOrder(self.rbStereo, self.gvHistory)
        QWidget.setTabOrder(self.gvHistory, self.tbResetAbs)

        self.retranslateUi(QtMeter)
        self.buttonBox.accepted.connect(QtMeter.accept)
        self.buttonBox.rejected.connect(QtMeter.reject)

        self.cbSampleHz.setCurrentIndex(5)
        self.cbSampleSize.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(QtMeter)
    # setupUi

    def retranslateUi(self, QtMeter):
        QtMeter.setWindowTitle(QCoreApplication.translate("QtMeter", u"Qt Audio Meter", None))
#if QT_CONFIG(whatsthis)
        QtMeter.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.dBMeter.setToolTip(QCoreApplication.translate("QtMeter", u"When audio is started will update every <Meter Update Period> showing the audio level of <Sample Window> of data from the default input device in self-relative dB", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pbStartStop.setToolTip(QCoreApplication.translate("QtMeter", u"Push to start sampling audio and updating the meter", None))
#endif // QT_CONFIG(tooltip)
        self.pbStartStop.setText(QCoreApplication.translate("QtMeter", u"Start", None))
        self.label.setText(QCoreApplication.translate("QtMeter", u"dB", None))
        self.label_2.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_3.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_4.setText(QCoreApplication.translate("QtMeter", u"0", None))
        self.label_5.setText(QCoreApplication.translate("QtMeter", u"-3", None))
        self.label_6.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_7.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_8.setText(QCoreApplication.translate("QtMeter", u"-6", None))
        self.label_9.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_10.setText(QCoreApplication.translate("QtMeter", u"-9", None))
        self.label_11.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_12.setText(QCoreApplication.translate("QtMeter", u"-15", None))
        self.label_13.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_14.setText(QCoreApplication.translate("QtMeter", u"-21", None))
        self.label_15.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_16.setText(QCoreApplication.translate("QtMeter", u"-27", None))
        self.label_17.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_18.setText(QCoreApplication.translate("QtMeter", u"-36", None))
        self.label_19.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_20.setText(QCoreApplication.translate("QtMeter", u"-45", None))
        self.label_21.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_22.setText(QCoreApplication.translate("QtMeter", u"-54", None))
        self.label_23.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_24.setText(QCoreApplication.translate("QtMeter", u"-66", None))
        self.label_25.setText(QCoreApplication.translate("QtMeter", u"|", None))
        self.label_26.setText(QCoreApplication.translate("QtMeter", u"-78", None))
        self.label_27.setText(QCoreApplication.translate("QtMeter", u"Meter Frame Rate:", None))
#if QT_CONFIG(tooltip)
        self.dsbUpdatePeriod.setToolTip(QCoreApplication.translate("QtMeter", u"Set the update period for the meter control in seconds. This period is not guaranteed, especially at lower values.", None))
#endif // QT_CONFIG(tooltip)
        self.label_28.setText(QCoreApplication.translate("QtMeter", u"s", None))
        self.label_29.setText(QCoreApplication.translate("QtMeter", u"Sample Window:", None))
#if QT_CONFIG(tooltip)
        self.dsbSampleWindow.setToolTip(QCoreApplication.translate("QtMeter", u"The duration of audio sample data to show the signal level for", None))
#endif // QT_CONFIG(tooltip)
        self.label_30.setText(QCoreApplication.translate("QtMeter", u"s", None))
        self.label_31.setText(QCoreApplication.translate("QtMeter", u"Sample Rate:", None))
        self.cbSampleHz.setItemText(0, QCoreApplication.translate("QtMeter", u"8000", None))
        self.cbSampleHz.setItemText(1, QCoreApplication.translate("QtMeter", u"11025", None))
        self.cbSampleHz.setItemText(2, QCoreApplication.translate("QtMeter", u"16000", None))
        self.cbSampleHz.setItemText(3, QCoreApplication.translate("QtMeter", u"22050", None))
        self.cbSampleHz.setItemText(4, QCoreApplication.translate("QtMeter", u"32000", None))
        self.cbSampleHz.setItemText(5, QCoreApplication.translate("QtMeter", u"44100", None))
        self.cbSampleHz.setItemText(6, QCoreApplication.translate("QtMeter", u"48000", None))
        self.cbSampleHz.setItemText(7, QCoreApplication.translate("QtMeter", u"88200", None))
        self.cbSampleHz.setItemText(8, QCoreApplication.translate("QtMeter", u"96000", None))
        self.cbSampleHz.setItemText(9, QCoreApplication.translate("QtMeter", u"192000", None))

#if QT_CONFIG(tooltip)
        self.cbSampleHz.setToolTip(QCoreApplication.translate("QtMeter", u"Select an audio data sample rate (some listed rates will not be supported by some audio devices)", None))
#endif // QT_CONFIG(tooltip)
        self.label_32.setText(QCoreApplication.translate("QtMeter", u"Hz", None))
        self.label_33.setText(QCoreApplication.translate("QtMeter", u"Sample Size:", None))
        self.cbSampleSize.setItemText(0, QCoreApplication.translate("QtMeter", u"8-bit", None))
        self.cbSampleSize.setItemText(1, QCoreApplication.translate("QtMeter", u"16-bit", None))
        self.cbSampleSize.setItemText(2, QCoreApplication.translate("QtMeter", u"24-bit", None))
        self.cbSampleSize.setItemText(3, QCoreApplication.translate("QtMeter", u"32-bit", None))
        self.cbSampleSize.setItemText(4, QCoreApplication.translate("QtMeter", u"32-bit Float", None))

#if QT_CONFIG(tooltip)
        self.sbFramesPerSecond.setToolTip(QCoreApplication.translate("QtMeter", u"Set the update frequency for the meter control in Hz. This rate is not guaranteed, especially at higher values.", None))
#endif // QT_CONFIG(tooltip)
        self.label_34.setText(QCoreApplication.translate("QtMeter", u"Hz", None))
        self.label_35.setText(QCoreApplication.translate("QtMeter", u"or", None))
#if QT_CONFIG(tooltip)
        self.cbAutoWindow.setToolTip(QCoreApplication.translate("QtMeter", u"Let the application choose a sample window based on the update period/frequency", None))
#endif // QT_CONFIG(tooltip)
        self.cbAutoWindow.setText(QCoreApplication.translate("QtMeter", u"Choose automatically", None))
#if QT_CONFIG(tooltip)
        self.gvHistory.setToolTip(QCoreApplication.translate("QtMeter", u"The background shows color representing the sky through the day. Long term meter levels are shown where they occurred during the day.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pbSettings.setToolTip(QCoreApplication.translate("QtMeter", u"Click to view and change the application settings", None))
#endif // QT_CONFIG(tooltip)
        self.pbSettings.setText(QCoreApplication.translate("QtMeter", u"Settings", None))
        self.label_36.setText(QCoreApplication.translate("QtMeter", u"_", None))
        self.label_37.setText(QCoreApplication.translate("QtMeter", u"_", None))
        self.label_38.setText(QCoreApplication.translate("QtMeter", u"dB", None))
        self.gbChannels.setTitle(QCoreApplication.translate("QtMeter", u"Channels", None))
#if QT_CONFIG(tooltip)
        self.rbMono.setToolTip(QCoreApplication.translate("QtMeter", u"Select to monitor a single channel (mono) input", None))
#endif // QT_CONFIG(tooltip)
        self.rbMono.setText(QCoreApplication.translate("QtMeter", u"Mono", None))
#if QT_CONFIG(tooltip)
        self.rbStereo.setToolTip(QCoreApplication.translate("QtMeter", u"Select to monitor a two channel (stereo) input", None))
#endif // QT_CONFIG(tooltip)
        self.rbStereo.setText(QCoreApplication.translate("QtMeter", u"Stereo", None))
        self.gbAbs.setTitle(QCoreApplication.translate("QtMeter", u"Absolute (dB):", None))
        self.lblAbsMin.setText(QCoreApplication.translate("QtMeter", u"Min:", None))
        self.lblAbsMax.setText(QCoreApplication.translate("QtMeter", u"Max:", None))
#if QT_CONFIG(tooltip)
        self.tbResetAbs.setToolTip(QCoreApplication.translate("QtMeter", u"Click to reset the absolute min/max and start fresh tracking of them", None))
#endif // QT_CONFIG(tooltip)
        self.tbResetAbs.setText(QCoreApplication.translate("QtMeter", u"...", None))
#if QT_CONFIG(tooltip)
        self.gvSpecHistory.setToolTip(QCoreApplication.translate("QtMeter", u"<html><head/><body><p>The audio spectrum observed through the day over a background with color representing the sky through the day. At any time a vertical line of pixels is the spectrum. &quot;Relative&quot; signal strength at each frequency is shown. Low to high relative strength in low to high transparency. Because relative strength is used then at quiet times there is actually less transparency across the whole vertical line for that time, but also little difference between any two pixels in the line. If there is regularly very high signal strength at any vertical positions it can obscure other part of the spectrum. Create an audio filter using the Spectrum tab of the Settings dialog to help. Power ratio probably works best when there is little variation in power between frequencies, dB probably works best when there are few strong signals that don't vary much in frequency.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.lblSpecMinF.setText(QCoreApplication.translate("QtMeter", u"0  ", None))
        self.label_43.setText(QCoreApplication.translate("QtMeter", u"_", None))
        self.label_39.setText(QCoreApplication.translate("QtMeter", u"f (Hz)", None))
        self.label_40.setText(QCoreApplication.translate("QtMeter", u"_", None))
        self.label_41.setText(QCoreApplication.translate("QtMeter", u"0", None))
        self.label_42.setText(QCoreApplication.translate("QtMeter", u"-90", None))
        self.lblSpecMaxF.setText(QCoreApplication.translate("QtMeter", u"16k", None))
#if QT_CONFIG(tooltip)
        self.gbSpectrumRatio.setToolTip(QCoreApplication.translate("QtMeter", u"Choose whether to show the spectrum view based on power level or dB", None))
#endif // QT_CONFIG(tooltip)
        self.gbSpectrumRatio.setTitle(QCoreApplication.translate("QtMeter", u"Ratios:", None))
        self.rbSpectrumRatiodB.setText(QCoreApplication.translate("QtMeter", u"dB", None))
        self.rbSpectrumRatioPower.setText(QCoreApplication.translate("QtMeter", u"Power", None))
    # retranslateUi

